### PR TITLE
Add zettle plugin to wordpress website

### PR DESCRIPTION
**Pull request by robertdijk**
This PR adds my Zettle Stock WordPress plugin to the website.
This plugin connects to Zettle and allows us to show the current stock of our items on our website.
This will be used for the book sale.

### CODE REVIEW

**Comment by robertdijk** [comment]
Is this all I have to do to deploy it? Does it now also auto-update when I update the plugin?

**Comment by JoepdeJong** [comment]
> Is this all I have to do to deploy it? Does it now also auto-update when I update the plugin?

yes.


but i think it is better to fork your repo into our organisation. where did you get the sourcecode from?

**Comment by JoepdeJong** [comment]
oh, the website only updates the plugins when it is redeployed. changing your repo does not trigger a deployment.

**Comment by robertdijk** [comment]
> but i think it is better to fork your repo into our organisation. where did you get the sourcecode from? maybe we can link it to that to ensure we get updates.

I wrote it 😋.
But I can still fork it on wisvch. Should I?

And how do the updates work now for the CH theme and CH plug-in?
Because I remember changing the theme and it was deployed within minutes.

**Comment by JoepdeJong** [comment]
> I wrote it 😋.

cool :)

> And how do the updates work now for the CH theme and CH plug-in?
> Because I remember changing the theme and it was deployed within minutes.

see
https://github.com/WISVCH/website/blob/9719b6500acf1df7a29b053d6a8ebad0c921a19d/entrypoint.sh#L44C1-L59C3

both are pulled upon initialising the pod. as far as i know, this is only triggered when https://github.com/WISVCH/website is updated, or when somebody manually triggers a new deployment. 

as far as I know, updating https://github.com/WISVCH/rechallenge or https://github.com/WISVCH/wisvch-wordpress-plugin does not trigger a new build. maybe we can implement a hook that does this?

**Comment by robertdijk** [comment]
I now transferred the repo to the CH organization (not my problem anymore 😋) so that should be good now.

For the deployment: I don't have enough rights to manually trigger a rebuild I think 🥺

**Pull request merged**
